#ifndef _ERROR_DEF_H
#define _ERROR_DEF_H

#define ERROR_NO 0
#define ERROR_NO_FILES -1
#define ERROR_SHMOPEN_FAIL -2
#define ERROR_FTRUNCATE_FAIL -3
#define ERROR_MMAP_FAIL -4
#define ERROR_SEMOPEN_FAIL -5
#define ERROR_FIFO_CREATION_FAIL -6
#define ERROR_FIFO_OPEN_FAIL -7
#define ERROR_FILE_OPEN_FAIL -8
#define ERROR_NOT_ENOUGH_ARGUMENTS -9
#define ERROR_NO_APPLICATION_PID -10
#define ERROR_MREMAP_FAIL -11

#endif
